### ISSUE TITLE
PCI passthrough: mpt3sas firmware fault inside guest

### ISSUE THREAD

**Issue by cuinutanix** [open-power-host-os/linux#10] opened 2017-01-23 17:06 UTC
This is the PCI device I'm passing through to a guest VM:

0001:03:00.0 Serial Attached SCSI controller [0107]: LSI Logic / Symbios Logic SAS3008 PCI-Express Fusion-MPT SAS-3 [1000:0097] (rev 02)

Inside the guest, the mpt3sas driver fails to initialize due to firmware faults. Sometimes when it does initialize it ends up getting IO errors.

Host is running HostOS with kernel 4.9.0 and qemu 2.7.0. Guest OS is stock CentOS 7.3.

Logs and config attached.
[guest-xml.txt](https://github.com/open-power-host-os/linux/files/724390/guest-xml.txt)
[guest-dmesg.txt](https://github.com/open-power-host-os/linux/files/724384/guest-dmesg.txt)
[host-dmesg.txt](https://github.com/open-power-host-os/linux/files/724385/host-dmesg.txt)

**Comment by rmatinata-ibm** [comment] 2017-01-23 18:05
I'd ask Brian K. to take a look into this, as well as possibly @aik ... 
Also, @laggarcia FYI

**Comment by rmatinata-ibm** [comment] 2017-01-23 18:18
Now adding @bjking1 to the discussion as well....

**Comment by bjking1** [comment] 2017-01-23 18:24
So, this adapter has never been tested in PCI passthrough mode on Power before. Looking at the host dmesg, I don't see mpt3sas loading, so are you blacklisting the driver in the host? It might be worth trying to blacklist mpt3sas in petitboot as well, since then the adapter should be largely untouched until the guest boots. Can you add:

modprobe.blacklist=mpt3sas

to the skiboot command line?

**Comment by cuinutanix** [comment] 2017-01-23 22:35
How do I change "skiboot command line"?

**Comment by rmatinata-ibm** [comment] 2017-01-24 00:16
Please try something like this, while in the Host OS:

`nvram -p ibm,skiboot --update-config bootargs="console=tty0 console=hvc0 quiet modprobe.blacklist=mpt3sas"`

**Comment by mfoliveira** [comment] 2017-02-09 19:02
This issue can be closed. 

It is resolved with this commit in qemu:
https://github.com/open-power-host-os/qemu/commit/bb80805d7d5b14e886e769b5938b459a3592d882

Root cause is without that patch the BAR1 addresses can't be mapped (too close to the MSI-X region), and the MMIO writes are trapped into qemu, which may cause problems in the driver's MMIO access since VFIO doesn't support to emulate qword MMIO read/write yet.  (thanks Yongji Xie for the details)

During the driver load time, several threads write to the adapter's doorbell register (for sending SCSI commands in this case), and some of them got scheduled in/out at an unfortunate time.

The workaround for this problem at the guest driver code is to guard the writeq() call w/ a spinlock (similarly done in the 32-bit version just below it, which uses 2 writes), plus a memory barrier after writeq() but still guarded by the spinlock.

Obviously the workaround is not required with the fix in qemu.

**Comment by rmatinata-ibm** [comment] 2017-02-09 20:08
Fix by open-power-host-os/qemu@bb80805.

**Closed as completed by rmatinata-ibm** 2017-02-09 20:08 UTC
